name: Update Submodules

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # This will checkout submodules as well

    - name: Update submodules
      run: |
        git submodule update --remote
        git add .
        git commit -m "Update submodules"
        git push
